apiVersion: v1
kind: Config
preferences:
clusters:
  - name: ${name}
    cluster:
      certificate-authority-data: ${certificate-authority-data}
      server: ${server}
users:
  - name: ${name}
    user:
      auth-provider:
        name: gcp
        config:
          cmd-path: gcloud
          cmd-args: config config-helper --format=json
          expiry-key: '{.credential.token_expiry}'
          token-key: '{.credential.access_token}'
contexts:
  - name: ${name}
    context:
      cluster: ${name}
      user: ${name}
current-context: ${name}
